### ISSUE TITLE
Move away from bitstrings, abstract SST away from ProVerif and block the use of a bitstring type in SST

### ISSUE THREAD

**Issue by Hundter** [Areedtz/st2rs#16]
The implementation we've done for AWE is quite similar to ProVerif in a few ways. One way, is that we make use of bitstring as a type, and use the ProVerif properties of it like the fact that a tuple is a bitstring.
This should be changed to be more descriptive, and not rely too muh on the bitstring properties in ProVerif.

Seeing as bitstring has these properties, we would also like to block the use of bitstring as a type to prevent unwanted behavior in the ProVerif verification.

- [x] Rewrite the AWE implementation, so that it doesn't use bitstrings
  - [x] Remember to check the implicit use of tuples = bitstring
- [x] Verify that the AWE implementation still runs in ProVerif after these changes
- [x] Look into implementing a compiler error, if a type of the name "bitstring" is used in SST

---
Remark ❗
- Avoiding `bitstring` creates issues with our typing system -> therefore we need to reconsider how to better infer types or create a more strongly-typed SST.

**Comment by Areedtz** [comment]
Closing this, as it was fixed as a part of #24
